# Generated by Django 5.0.6 on 2024-06-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genra_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_img', models.ImageField(upload_to='media', verbose_name='images')),
                ('book_price', models.PositiveIntegerField(default=100)),
                ('book_avilability', models.BooleanField(default=False)),
                ('book_detail', models.TextField(max_length=500)),
                ('book_genra', models.ManyToManyField(to='models_testing_app.genra', verbose_name='book_genra')),
            ],
        ),
    ]
