# Generated by Django 5.0.6 on 2024-06-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_testing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genra',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
