# Generated by Django 5.0.6 on 2024-06-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_testing_app', '0002_alter_book_id_alter_genra_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='images'),
        ),
    ]
