# Generated by Django 5.0.6 on 2024-06-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_testing_app', '0003_alter_book_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(upload_to='media', verbose_name='images'),
        ),
    ]
