# Generated by Django 5.0.6 on 2024-06-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_testing_app', '0004_alter_book_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_avilability',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_detail',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_genra',
            field=models.ManyToManyField(blank=True, null=True, to='models_testing_app.genra', verbose_name='book_genra'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_price',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
