# Generated by Django 5.0.6 on 2024-06-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_testing_app', '0006_alter_book_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_genra',
            field=models.ManyToManyField(to='models_testing_app.genra', verbose_name='book_genra'),
        ),
    ]
