# Generated by Django 5.0.6 on 2024-06-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_testing_app', '0007_alter_book_book_genra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='images'),
        ),
    ]
