# Generated by Django 5.0.6 on 2024-07-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_reviews_text_alter_reviews_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reviews_img',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='images'),
        ),
    ]
