# Generated by Django 5.0.6 on 2024-07-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_reply_remove_reviews_text_reviews_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
