# Generated by Django 5.0.6 on 2024-07-01 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Q_name',
            fields=[
                ('quiz_name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_types',
            fields=[
                ('type_name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='options',
            fields=[
                ('quiz_question', models.CharField(blank=True, max_length=50)),
                ('option_A', models.CharField(max_length=50)),
                ('option_B', models.CharField(max_length=50)),
                ('option_C', models.CharField(max_length=50)),
                ('option_D', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_name', models.ManyToManyField(to='mcq_web.q_name')),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('options', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mcq_web.options')),
                ('quiz_name', models.ManyToManyField(to='mcq_web.q_name')),
            ],
        ),
        migrations.CreateModel(
            name='quiz_data',
            fields=[
                ('quiz_details', models.TextField(blank=True, max_length=100, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz', models.ManyToManyField(to='mcq_web.quiz')),
                ('quiz_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz_name', models.ManyToManyField(to='mcq_web.q_name')),
                ('quiz_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mcq_web.quiz_types')),
            ],
        ),
        migrations.CreateModel(
            name='quiz_history',
            fields=[
                ('quiz_score', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq_web.quiz_data')),
                ('quiz_name', models.ManyToManyField(to='mcq_web.q_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
